config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/' => 'home#index', as: 'root'

  resources :users do
    member do
      get 'generate_report' => 'users#generate_report'
    end
    resources :generated_reports
  end

end

app/models/generated_report.rb
class GeneratedReport < ActiveRecord::Base
	belongs_to :user

	validates_presence_of :user_id, :external_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	attr_accessor :login
  has_many :generated_reports   

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end    

  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_hash).first
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/generated_reports_controller.rb
class GeneratedReportsController < ApplicationController
	before_action :authenticate_user!

	def index
		@generated_reports = current_user.generated_reports
	end

	def update
		@generated_report = GeneratedReport.find(params[:id])
		@generated_report.update_attributes!(generated_reports_params)
		redirect_to user_generated_reports_path(current_user.id)
	end

	private 

	def generated_reports_params
		params.require(:generated_report).permit(:comment)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	# FrontEnd validation needed
	def generate_report
		campaign_id = params[:campaign_id]
		if campaign_id.present?
			report_generator = ReportGeneratorQuery.new(params[:campaign_id], current_user.id)
			@generated_report = report_generator.run
			render :show
		end

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/generated_reports/index.html.erb
<%- if @generated_reports %>
	<ul>
		<%- @generated_reports.each do |report| %>
	    <li>
	    	<%= report.campaign_id %>
	    	<%= report.created_at %>
	    	<%= form_for report, url: user_generated_report_path(current_user.id, report.id), method: :patch do |f| %>
		    	<%= f.text_area :comment %>
		    	<%= f.submit 'Update Report Comments' %>
	    	<% end %>
	    </li>
    <% end %>
	</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReportGenerator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container-narrow">
	  <div class="masthead">
	    <%= render 'layouts/user_header' %>
	    <h3 class="muted"><%= link_to "SimpleDevise", root_path %></h3>
	    <h5 class="muted">A demo of using SimpleDB with Devise</h5>
	  </div>
	  <hr />
	  <%= yield %>
	</div>

</body>
</html>

app/views/users/show.html.erb
<%= @generated_report %>